name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 31.97.49.109 >> ~/.ssh/known_hosts

      - name: Deploy with PM2
        run: ssh deployer@31.97.49.109 "cd /var/www/kimmohito/kimmohito-app && git pull origin main && pm2 restart kimmohito-api"
